/**
 * @file sitl_test.c
 * @brief Continuous SITL (Software-In-The-Loop) test.
 *
 * Reads nav_state trajectory from JSON (generated by MATLAB),
 * runs gnc_step() for every time step, writes fin_cmd + phase
 * results to JSON for MATLAB comparison.
 *
 * Build (from project root):
 *   gcc -o sitl_test.exe src/sitl_test.c src/fcs/autopilot.c src/fcs/guidance.c src/fcs/flight_phase.c src/fcs/gnc_main.c src/avionics/recovery.c -Iinclude -lm -DSITL_TEST
 *
 * Run:
 *   ./sitl_test sitl_nav_data.json sitl_results.json
 *
 * Then in MATLAB:
 *   run_sitl_compare
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdbool.h>

#include "gnc_types.h"
#include "flight_phase.h"
#include "guidance.h"
#include "autopilot.h"
#include "gnc_config.h"
#include "gnc_main.h"

/* ================================================================
 *  Minimal JSON parser (numbers + arrays only, no dependencies)
 * ================================================================ */

/* Skip whitespace */
static const char* skip_ws(const char* p) {
    while (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r') p++;
    return p;
}

/* Find key in JSON object, return pointer to value */
static const char* json_find_key(const char* json, const char* key) {
    char pattern[128];
    snprintf(pattern, sizeof(pattern), "\"%s\"", key);
    const char* p = strstr(json, pattern);
    if (!p) return NULL;
    p += strlen(pattern);
    p = skip_ws(p);
    if (*p == ':') p++;
    return skip_ws(p);
}

/* Parse float */
static float json_read_float(const char** pp) {
    const char* p = skip_ws(*pp);
    char* end;
    float v = (float)strtod(p, &end);
    *pp = end;
    return v;
}

/* Parse float array, return count */
static int json_read_float_array(const char* p, float* out, int max_n) {
    p = skip_ws(p);
    if (*p != '[') return 0;
    p++;
    int n = 0;
    while (n < max_n) {
        p = skip_ws(p);
        if (*p == ']') break;
        char* end;
        out[n++] = (float)strtod(p, &end);
        p = end;
        p = skip_ws(p);
        if (*p == ',') p++;
    }
    return n;
}

/* Parse array of arrays: [[...],[...],...] */
static int json_read_2d_float_array(const char* p, float** rows, int* cols_out, int max_rows, int max_cols) {
    p = skip_ws(p);
    if (*p != '[') return 0;
    p++;
    int n_rows = 0;
    while (n_rows < max_rows) {
        p = skip_ws(p);
        if (*p == ']') break;
        if (*p == '[') {
            int nc = json_read_float_array(p, rows[n_rows], max_cols);
            if (n_rows == 0 && cols_out) *cols_out = nc;
            n_rows++;
            /* Skip past closing ']' */
            int depth = 0;
            while (*p) {
                if (*p == '[') depth++;
                if (*p == ']') { depth--; if (depth == 0) { p++; break; } }
                p++;
            }
        }
        p = skip_ws(p);
        if (*p == ',') p++;
    }
    return n_rows;
}

/* ================================================================
 *  Main
 * ================================================================ */

#define MAX_STEPS 20000

int main(int argc, char* argv[]) {
    const char* input_file  = (argc > 1) ? argv[1] : "sitl_nav_data.json";
    const char* output_file = (argc > 2) ? argv[2] : "sitl_results.json";
    const char* config_name = (argc > 3) ? argv[3] : "default";

    /* 1. Read input JSON */
    FILE* f = fopen(input_file, "r");
    if (!f) {
        fprintf(stderr, "Cannot open %s\n", input_file);
        return 1;
    }
    fseek(f, 0, SEEK_END);
    long fsize = ftell(f);
    fseek(f, 0, SEEK_SET);
    char* json = (char*)malloc(fsize + 1);
    fread(json, 1, fsize, f);
    json[fsize] = '\0';
    fclose(f);

    printf("=== SITL Test ===\n");
    printf("Input: %s (%ld bytes)\n", input_file, fsize);

    /* 2. Parse N */
    const char* p_n = json_find_key(json, "N");
    int N = (int)strtol(p_n, NULL, 10);
    if (N <= 0 || N > MAX_STEPS) {
        fprintf(stderr, "Invalid N=%d\n", N);
        free(json);
        return 1;
    }
    printf("Steps: %d\n", N);

    /* 3. Parse arrays */
    float* t_arr       = (float*)calloc(N, sizeof(float));
    float* pos_data    = (float*)calloc(N * 3, sizeof(float));
    float* vel_data    = (float*)calloc(N * 3, sizeof(float));
    float* quat_data   = (float*)calloc(N * 4, sizeof(float));
    float* omega_data  = (float*)calloc(N * 3, sizeof(float));
    float* accel_data  = (float*)calloc(N * 3, sizeof(float));
    float* wind_data   = (float*)calloc(N * 3, sizeof(float));
    float* airspeed_arr = (float*)calloc(N, sizeof(float));

    /* t */
    {
        const char* p = json_find_key(json, "t");
        json_read_float_array(p, t_arr, N);
    }

    /* pos_ned [N][3] */
    {
        const char* p = json_find_key(json, "pos_ned");
        p = skip_ws(p);
        if (*p == '[') {
            p++;
            for (int i = 0; i < N; i++) {
                p = skip_ws(p);
                if (*p == '[') {
                    p++;
                    pos_data[i*3+0] = (float)strtod(p, (char**)&p); p = skip_ws(p); if (*p==',') p++;
                    pos_data[i*3+1] = (float)strtod(p, (char**)&p); p = skip_ws(p); if (*p==',') p++;
                    pos_data[i*3+2] = (float)strtod(p, (char**)&p); p = skip_ws(p);
                    if (*p == ']') p++;
                }
                p = skip_ws(p);
                if (*p == ',') p++;
            }
        }
    }

    /* vel_ned [N][3] */
    {
        const char* p = json_find_key(json, "vel_ned");
        p = skip_ws(p);
        if (*p == '[') {
            p++;
            for (int i = 0; i < N; i++) {
                p = skip_ws(p);
                if (*p == '[') {
                    p++;
                    vel_data[i*3+0] = (float)strtod(p, (char**)&p); p = skip_ws(p); if (*p==',') p++;
                    vel_data[i*3+1] = (float)strtod(p, (char**)&p); p = skip_ws(p); if (*p==',') p++;
                    vel_data[i*3+2] = (float)strtod(p, (char**)&p); p = skip_ws(p);
                    if (*p == ']') p++;
                }
                p = skip_ws(p);
                if (*p == ',') p++;
            }
        }
    }

    /* quat [N][4] */
    {
        const char* p = json_find_key(json, "quat");
        p = skip_ws(p);
        if (*p == '[') {
            p++;
            for (int i = 0; i < N; i++) {
                p = skip_ws(p);
                if (*p == '[') {
                    p++;
                    quat_data[i*4+0] = (float)strtod(p, (char**)&p); p = skip_ws(p); if (*p==',') p++;
                    quat_data[i*4+1] = (float)strtod(p, (char**)&p); p = skip_ws(p); if (*p==',') p++;
                    quat_data[i*4+2] = (float)strtod(p, (char**)&p); p = skip_ws(p); if (*p==',') p++;
                    quat_data[i*4+3] = (float)strtod(p, (char**)&p); p = skip_ws(p);
                    if (*p == ']') p++;
                }
                p = skip_ws(p);
                if (*p == ',') p++;
            }
        }
    }

    /* omega_b [N][3] */
    {
        const char* p = json_find_key(json, "omega_b");
        p = skip_ws(p);
        if (*p == '[') {
            p++;
            for (int i = 0; i < N; i++) {
                p = skip_ws(p);
                if (*p == '[') {
                    p++;
                    omega_data[i*3+0] = (float)strtod(p, (char**)&p); p = skip_ws(p); if (*p==',') p++;
                    omega_data[i*3+1] = (float)strtod(p, (char**)&p); p = skip_ws(p); if (*p==',') p++;
                    omega_data[i*3+2] = (float)strtod(p, (char**)&p); p = skip_ws(p);
                    if (*p == ']') p++;
                }
                p = skip_ws(p);
                if (*p == ',') p++;
            }
        }
    }

    /* accel_b [N][3] */
    {
        const char* p = json_find_key(json, "accel_b");
        p = skip_ws(p);
        if (*p == '[') {
            p++;
            for (int i = 0; i < N; i++) {
                p = skip_ws(p);
                if (*p == '[') {
                    p++;
                    accel_data[i*3+0] = (float)strtod(p, (char**)&p); p = skip_ws(p); if (*p==',') p++;
                    accel_data[i*3+1] = (float)strtod(p, (char**)&p); p = skip_ws(p); if (*p==',') p++;
                    accel_data[i*3+2] = (float)strtod(p, (char**)&p); p = skip_ws(p);
                    if (*p == ']') p++;
                }
                p = skip_ws(p);
                if (*p == ',') p++;
            }
        }
    }

    /* wind_est [N][3] */
    {
        const char* p = json_find_key(json, "wind_est");
        p = skip_ws(p);
        if (*p == '[') {
            p++;
            for (int i = 0; i < N; i++) {
                p = skip_ws(p);
                if (*p == '[') {
                    p++;
                    wind_data[i*3+0] = (float)strtod(p, (char**)&p); p = skip_ws(p); if (*p==',') p++;
                    wind_data[i*3+1] = (float)strtod(p, (char**)&p); p = skip_ws(p); if (*p==',') p++;
                    wind_data[i*3+2] = (float)strtod(p, (char**)&p); p = skip_ws(p);
                    if (*p == ']') p++;
                }
                p = skip_ws(p);
                if (*p == ',') p++;
            }
        }
    }

    /* airspeed [N] */
    {
        const char* p = json_find_key(json, "airspeed");
        json_read_float_array(p, airspeed_arr, N);
    }

    /* phase [N] — ground truth from MATLAB sim, overrides C phase_update */
    int* phase_in = (int*)calloc(N, sizeof(int));
    int has_phase_input = 0;
    {
        const char* p = json_find_key(json, "phase");
        if (p) {
            p = skip_ws(p);
            if (*p == '[') {
                p++;
                for (int i = 0; i < N; i++) {
                    p = skip_ws(p);
                    phase_in[i] = (int)strtol(p, (char**)&p, 10);
                    p = skip_ws(p);
                    if (*p == ',') p++;
                }
                has_phase_input = 1;
                printf("Phase sync: using ground truth from JSON\n");
            }
        }
    }

    free(json);

    /* 4. Initialize GNC */
    gnc_config_t cfg;
    if (strcmp(config_name, "flight1") == 0) {
        cfg = gnc_config_flight1();
        printf("Config: flight1 (attitude only, no guidance)\n");
    } else {
        cfg = gnc_config_default();
        printf("Config: default (full guidance)\n");
    }
    gnc_state_t  state;
    phase_state_t ps;
    recovery_state_t rcv;
    gnc_init(&state, &ps, &rcv);

    /* 5. Run GNC loop */
    float* fin_out   = (float*)calloc(N * 4, sizeof(float));
    float* nz_out    = (float*)calloc(N, sizeof(float));
    float* ny_out    = (float*)calloc(N, sizeof(float));
    int*   phase_out = (int*)calloc(N, sizeof(int));

    printf("Running GNC...\n");

    for (int k = 0; k < N; k++) {
        nav_state_t nav = {0};
        nav.pos_ned  = (vec3_t){pos_data[k*3+0],  pos_data[k*3+1],  pos_data[k*3+2]};
        nav.vel_ned  = (vec3_t){vel_data[k*3+0],  vel_data[k*3+1],  vel_data[k*3+2]};
        nav.quat     = (quat_t){quat_data[k*4+0], quat_data[k*4+1], quat_data[k*4+2], quat_data[k*4+3]};
        nav.omega_b  = (vec3_t){omega_data[k*3+0], omega_data[k*3+1], omega_data[k*3+2]};
        nav.accel_b  = (vec3_t){accel_data[k*3+0], accel_data[k*3+1], accel_data[k*3+2]};
        nav.wind_est = (vec3_t){wind_data[k*3+0],  wind_data[k*3+1],  wind_data[k*3+2]};
        nav.airspeed = airspeed_arr[k];
        nav.timestamp_ms = (uint32_t)(t_arr[k] * 1000.0f);
        nav.valid = true;

        flight_phase_t cur_phase;
        if (has_phase_input) {
            cur_phase = (flight_phase_t)phase_in[k];
            ps.phase = cur_phase;
        } else {
            cur_phase = phase_update(&ps, &nav, &cfg, t_arr[k]);
        }

        float nz_cmd = 0.0f;
        float ny_cmd = 0.0f;
        ap_output_t ap_out;
        memset(&ap_out, 0, sizeof(ap_out));

        switch (cur_phase) {
        case PHASE_RAIL:
            break;
        case PHASE_BOOST:
            ap_out = autopilot_step(0.0f, 0.0f, &nav, &cfg, &state.ap);
            /* Print last 3 BOOST steps before GUIDE */
            if (k < N-1 && has_phase_input && phase_in[k+1] == 2) {
                printf("[BOOST END k=%d t=%.4f] roll_int=%.8f roll_ramp=%.4f roll_e_prev=%.8f\n",
                       k, t_arr[k], state.ap.roll_int, state.ap.roll_ramp, state.ap.roll_e_prev);
                printf("  pitch_int=%.8f yaw_int=%.8f\n", state.ap.pitch_int, state.ap.yaw_int);
                printf("  da=%.6f de=%.6f dr=%.6f\n", ap_out.da_cmd, ap_out.de_cmd, ap_out.dr_cmd);
            }
            break;
        case PHASE_GUIDE:
            if (cfg.guidance_enabled) {
                guid_output_t gout = guidance_step(&nav, &cfg, &state.guid, t_arr[k]);
                nz_cmd = gout.nz_cmd;
                ny_cmd = gout.ny_cmd;
            }
            ap_out = autopilot_step(nz_cmd, ny_cmd, &nav, &cfg, &state.ap);
            {
                static int guide_dbg_count = 0;
                if (guide_dbg_count < 3) {
                    printf("[GUIDE DBG k=%d t=%.4f] nz=%.6f ny=%.6f\n", k, t_arr[k], nz_cmd, ny_cmd);
                    printf("  fin=[%.6f %.6f %.6f %.6f]\n",
                           ap_out.fin_cmd[0], ap_out.fin_cmd[1], ap_out.fin_cmd[2], ap_out.fin_cmd[3]);
                    printf("  de=%.6f dr=%.6f da=%.6f\n", ap_out.de_cmd, ap_out.dr_cmd, ap_out.da_cmd);
                    /* vb + phi_grav for debug */
                    quat_t qn2 = quat_normalize(nav.quat);
                    float R2[9]; quat_to_dcm_bn(qn2, R2);
                    vec3_t va2 = vec3_sub(nav.vel_ned, nav.wind_est);
                    vec3_t vb2 = dcm_bn_mul_vec(R2, va2);
                    float ub2 = fmaxf(vb2.x, 1.0f);
                    float adeg = fabsf(atan2f(vb2.z, ub2)) * 57.2958f;
                    float phi_grav = atan2f(R2[5], R2[8]);
                    printf("  vb=[%.2f %.2f %.2f] alpha=%.2f phi_grav=%.6f (%.2f deg)\n",
                           vb2.x, vb2.y, vb2.z, adeg, phi_grav, phi_grav*57.2958f);
                    printf("  R_BN[5]=%.6f R_BN[8]=%.6f\n", R2[5], R2[8]);
                    printf("  omega=[%.4f %.4f %.4f]\n",
                           nav.omega_b.x, nav.omega_b.y, nav.omega_b.z);
                    guide_dbg_count++;
                }
            }
            break;
        case PHASE_CPA:
            ap_out = autopilot_step(0.0f, 0.0f, &nav, &cfg, &state.ap);
            break;
        case PHASE_DESCENT:
            /* Fins off — parachute recovery */
            break;
        default:
            break;
        }

        fin_out[k*4+0] = ap_out.fin_cmd[0];
        fin_out[k*4+1] = ap_out.fin_cmd[1];
        fin_out[k*4+2] = ap_out.fin_cmd[2];
        fin_out[k*4+3] = ap_out.fin_cmd[3];
        nz_out[k]  = nz_cmd;
        ny_out[k]  = ny_cmd;
        phase_out[k] = (int)cur_phase;
    }

    printf("Done.\n");

    /* 6. Write output JSON */
    f = fopen(output_file, "w");
    if (!f) {
        fprintf(stderr, "Cannot open %s for writing\n", output_file);
        return 1;
    }

    fprintf(f, "{\n");
    fprintf(f, "  \"N\": %d,\n", N);

    /* fin_cmd [N][4] */
    fprintf(f, "  \"fin_cmd\": [\n");
    for (int k = 0; k < N; k++) {
        fprintf(f, "    [%.10e, %.10e, %.10e, %.10e]%s\n",
                fin_out[k*4+0], fin_out[k*4+1], fin_out[k*4+2], fin_out[k*4+3],
                (k < N-1) ? "," : "");
    }
    fprintf(f, "  ],\n");

    /* nz_cmd [N] */
    fprintf(f, "  \"nz_cmd\": [");
    for (int k = 0; k < N; k++) {
        fprintf(f, "%.10e%s", nz_out[k], (k < N-1) ? ", " : "");
    }
    fprintf(f, "],\n");

    /* ny_cmd [N] */
    fprintf(f, "  \"ny_cmd\": [");
    for (int k = 0; k < N; k++) {
        fprintf(f, "%.10e%s", ny_out[k], (k < N-1) ? ", " : "");
    }
    fprintf(f, "],\n");

    /* phase [N] */
    fprintf(f, "  \"phase\": [");
    for (int k = 0; k < N; k++) {
        fprintf(f, "%d%s", phase_out[k], (k < N-1) ? ", " : "");
    }
    fprintf(f, "]\n");

    fprintf(f, "}\n");
    fclose(f);

    printf("Output: %s\n", output_file);

    /* Cleanup */
    free(t_arr); free(pos_data); free(vel_data); free(quat_data);
    free(omega_data); free(accel_data); free(wind_data); free(airspeed_arr);
    free(fin_out); free(nz_out); free(ny_out); free(phase_out);
    free(phase_in);

    return 0;
}